name: callieccline
favicon: null
layout_spectrum: 0.37961
typography_spectrum: 0.7953105992637575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9dccc8'
    - '#000000'
    - '#c39375'
    - '#feebde'
    - '#5f5f5f'
  brandStrength: 0.5
  lightness: 0.04174284287728369
  saturation: 0.6721917476970702
  rhythmicContrast: 0.7720821041148156
purpose: []
