name: callieccline
favicon: null
layout_spectrum: 0.37961
typography_spectrum: 0.7953105992637575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0c0f'
    - '#ffffff'
    - '#ff11ca'
    - '#ff8d00'
    - '#00bdff'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
